#!/bin/bash
echo "=> Building the binary"
docker build \
    --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
    --build-arg DOCKER_TAG=$DOCKER_TAG \
    --build-arg VCS_REF=$(git rev-parse --short HEAD) \
    -t $IMAGE_NAME .
